[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 1000000
via_ir = true

[profile.test]
src = 'test'
verbosity = 3

[profile.base]
optimizer = true
optimizer_runs = 1000000
via_ir = true
libs = ["lib"]
allow_paths = ["node_modules", "contracts"]

[rpc_endpoints]
mainnet = "${ETH_RPC_URL}"
localhost = "http://localhost:8545"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
base = "${BASE_RPC_URL}"
base_goerli = "${BASE_GOERLI_RPC_URL}"

[etherscan]
# For when you want to verify the contracts
# etherscan_api_key = "${ETHERSCAN_API_KEY}"

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options