[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
solc_version = '0.8.23'
optimizer = true
optimizer_runs = 200

[profile.test]
src = 'test'
verbosity = 3

[rpc_endpoints]
mainnet = "${ETH_RPC_URL}"
localhost = "http://localhost:8545"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
# For when you want to verify the contracts
# etherscan_api_key = "${ETHERSCAN_API_KEY}"

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"